"""create workflow runs table

Revision ID: 65e376b56646
Revises: 97ebce976286
Create Date: 2026-08-10 11:10:00.250590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e376b56646'
down_revision: Union[str, Sequence[str], None] = '97ebce976286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='workflow_run_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_workflow_runs_id"),
        table_name="workflow_runs",
    )
    op.drop_table("workflow_runs")

    workflow_run_status = sa.Enum(
        "pending",
        "running",
        "completed",
        "failed",
        name="workflow_run_status",
    )
    workflow_run_status.drop(
        op.get_bind(),
        checkfirst=True,
    )
