"""allow nullable workflow prompt

Revision ID: 75d358cf2f0f
Revises: 65e376b56646
Create Date: 2026-08-12 16:10:40.045758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d358cf2f0f'
down_revision: Union[str, Sequence[str], None] = '65e376b56646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'prompt',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
